### ISSUE TITLE
[1.20.1] lootchests issue

### ISSUE THREAD

**Issue by Bass2style** [Aureljz/WhenDungeonsArise--Forge#22]
Hello,

i found an issue with the mod, loot chests and barrels in dungeons are generating, but they are empty.
i found nothing in the logs about errors générating those, so i'm not sure i can provide any usefull logs.

i'm actually running Forge 47.0.16, and WDA 2.1.56-BETA.

have a nice day.

**Comment by Aureljz** [comment]
Hey, just tested chests and barrels on the same version and they seem to be fine. However, someone else has mentioned this as well. Which structure are you trying to loot? Are you using any other mods? Do you have logs just in case?

**Comment by Bass2style** [comment]
Hello,

It's a bit late here, and my week-end is a bit full, but i'm checking that asap when i come back.

i already have a lot of mods, and it's a possible conflict. it seems that Rats village houses also have empty chests, te be confirmed, so it can be a conflict with another mod.

i try to provide logs etc monday, if it's not fixed until i try to figure out what's going on.

have a good night.

**Comment by Bass2style** [comment]
hello,

uh, i think i missclicked yesterday, the issue whas marked as closed by me. xD

i don't have the logs yet, but here are all my installed mods : https://gist.github.com/Bass2style/dd4b7f5d55aaffd1e4ef4c1dd038e116

i'm editing this comment with the log asap.

have a nice day.

edit :
well, i updated everything, mods and forge, and now it seems to work. yesterday i generated something like 8 maps with and without Lootr (i wasn't sure he was the problem), and now it seems okay for wathever reason. XD

**Comment by LookAliveKilljoy** [comment]
Hello,

I was having this issue as well. But, then I realized that I was a couple of updates behind on Forge (I was on 47.0.16). I am now on 47.0.19 and everything is spawning just fine.

I apologize for flagging that as an issue when it could have been easily resolved by an update.

**Comment by Bass2style** [comment]
Same, i was running Forge 47.0.16, i think they messed something with this build, the changelog talks about LootPool changes, maybe the culprit.
